// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Versus.API.Data;

#nullable disable

namespace Versus.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260610081028_AddIsPlayAgainToMatches")]
    partial class AddIsPlayAgainToMatches
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Versus.API.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IconUrl = "https://fontawesome.com/icons/classic/solid/clapperboard",
                            IsActive = true,
                            Name = "Movies",
                            Slug = "movies"
                        },
                        new
                        {
                            Id = 2,
                            IconUrl = "https://fontawesome.com/icons/classic/solid/desktop",
                            IsActive = true,
                            Name = "Series",
                            Slug = "series"
                        },
                        new
                        {
                            Id = 3,
                            IconUrl = "https://fontawesome.com/icons/classic/solid/music",
                            IsActive = true,
                            Name = "Music",
                            Slug = "music"
                        },
                        new
                        {
                            Id = 4,
                            IconUrl = "https://fontawesome.com/icons/classic/solid/person-running",
                            IsActive = true,
                            Name = "Sport",
                            Slug = "sport"
                        });
                });

            modelBuilder.Entity("Versus.API.Models.EloHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Delta")
                        .HasColumnType("real");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("RatingAfter")
                        .HasColumnType("real");

                    b.Property<float>("RatingBefore")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("MatchId");

                    b.ToTable("EloHistories");
                });

            modelBuilder.Entity("Versus.API.Models.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("EloRating")
                        .HasColumnType("real");

                    b.Property<string>("ExternalId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalSource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MatchCount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TierListId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TierListId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Versus.API.Models.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsPlayAgain")
                        .HasColumnType("bit");

                    b.Property<Guid>("LoserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("PlayedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TierListId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WinnerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LoserId");

                    b.HasIndex("SessionId");

                    b.HasIndex("TierListId");

                    b.HasIndex("WinnerId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("Versus.API.Models.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Versus.API.Models.TierList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CreatorSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatorSessionId");

                    b.ToTable("TierList");
                });

            modelBuilder.Entity("Versus.API.Models.EloHistory", b =>
                {
                    b.HasOne("Versus.API.Models.Item", "Item")
                        .WithMany("EloHistories")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Versus.API.Models.Match", "Match")
                        .WithMany("EloHistories")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Match");
                });

            modelBuilder.Entity("Versus.API.Models.Item", b =>
                {
                    b.HasOne("Versus.API.Models.TierList", "TierList")
                        .WithMany("Items")
                        .HasForeignKey("TierListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TierList");
                });

            modelBuilder.Entity("Versus.API.Models.Match", b =>
                {
                    b.HasOne("Versus.API.Models.Item", "Loser")
                        .WithMany("LoserMatches")
                        .HasForeignKey("LoserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Versus.API.Models.Session", "Session")
                        .WithMany("Matches")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Versus.API.Models.TierList", "TierList")
                        .WithMany("Matches")
                        .HasForeignKey("TierListId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Versus.API.Models.Item", "Winner")
                        .WithMany("WinnerMatches")
                        .HasForeignKey("WinnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Loser");

                    b.Navigation("Session");

                    b.Navigation("TierList");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("Versus.API.Models.TierList", b =>
                {
                    b.HasOne("Versus.API.Models.Category", "Category")
                        .WithMany("TierLists")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Versus.API.Models.Session", "CreatorSession")
                        .WithMany("TierLists")
                        .HasForeignKey("CreatorSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("CreatorSession");
                });

            modelBuilder.Entity("Versus.API.Models.Category", b =>
                {
                    b.Navigation("TierLists");
                });

            modelBuilder.Entity("Versus.API.Models.Item", b =>
                {
                    b.Navigation("EloHistories");

                    b.Navigation("LoserMatches");

                    b.Navigation("WinnerMatches");
                });

            modelBuilder.Entity("Versus.API.Models.Match", b =>
                {
                    b.Navigation("EloHistories");
                });

            modelBuilder.Entity("Versus.API.Models.Session", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("TierLists");
                });

            modelBuilder.Entity("Versus.API.Models.TierList", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Matches");
                });
#pragma warning restore 612, 618
        }
    }
}
